import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { db, sql } from '../db/client.js';
import {
  appraisals,
  auditEntries,
  cycles,
  departments,
  divisions,
  employees,
  evidence,
  jobTitles,
  kras,
  kraTemplateItems,
  kraTemplates,
  positions,
  squads,
  users,
} from '../db/schema.js';

const seedPassword = process.env.SEED_PASSWORD ?? 'demo1234';
const passwordHash = await bcrypt.hash(seedPassword, 12);

const userRows = [
  { id: 1, name: 'Andi Pratama', email: 'andi@performa.id' },
  { id: 2, name: 'Budi Santoso', email: 'budi@performa.id' },
  { id: 3, name: 'Citra Dewi', email: 'citra@performa.id' },
  { id: 4, name: 'Deni Wahyudi', email: 'deni@performa.id' },
  { id: 5, name: 'Eka Rahayu', email: 'eka@performa.id' },
  { id: 6, name: 'Fani Lestari', email: 'fani@performa.id' },
  { id: 7, name: 'Gilang Nugraha', email: 'gilang@performa.id' },
  { id: 8, name: 'Levi Pranata', email: 'levi@performa.id' },
  { id: 9, name: 'Aqmal Pratama', email: 'aqmal@performa.id' },
  { id: 10, name: 'Aqmal Rizky', email: 'aqmal.rizky@performa.id' },
  { id: 11, name: 'Aqmal Hakim', email: 'aqmal.hakim@performa.id' },
  { id: 12, name: 'Aqmal Firdaus', email: 'aqmal.firdaus@performa.id' },
  { id: 13, name: 'Aqmal Naufal', email: 'aqmal.naufal@performa.id' },
  { id: 14, name: 'Raka Mahendra', email: 'raka.mahendra@performa.id' },
  { id: 15, name: 'Nabila Putri', email: 'nabila.putri@performa.id' },
  { id: 16, name: 'Taufik Ramadhan', email: 'taufik.ramadhan@performa.id' },
  { id: 17, name: 'Salsa Anindita', email: 'salsa.anindita@performa.id' },
  { id: 18, name: 'Ilham Saputra', email: 'ilham.saputra@performa.id' },
  { id: 19, name: 'Maya Larasati', email: 'maya.larasati@performa.id' },
  { id: 20, name: 'Dimas Prakoso', email: 'dimas.prakoso@performa.id' },
  { id: 21, name: 'Rina Kurnia', email: 'rina.kurnia@performa.id' },
  { id: 22, name: 'Bagas Wicaksono', email: 'bagas.wicaksono@performa.id' },
  { id: 23, name: 'Siti Fauziah', email: 'siti.fauziah@performa.id' },
  { id: 24, name: 'Yudha Permana', email: 'yudha.permana@performa.id' },
  { id: 25, name: 'Kevin Santika', email: 'kevin.santika@performa.id' },
];

const divisionRows = [
  { id: 1, name: 'Technology' },
  { id: 2, name: 'Business' },
  { id: 3, name: 'Operations' },
  { id: 4, name: 'Corporate' },
];

const departmentRows = [
  { id: 1, name: 'Engineering', division: 'Technology', divId: 1 },
  { id: 2, name: 'Product', division: 'Technology', divId: 1 },
  { id: 3, name: 'Design', division: 'Technology', divId: 1 },
  { id: 4, name: 'Marketing', division: 'Business', divId: 2 },
  { id: 5, name: 'Finance', division: 'Corporate', divId: 4 },
  { id: 6, name: 'People (HR)', division: 'Corporate', divId: 4 },
];

const positionRows = [
  {
    id: 1,
    code: 'ENG-SE-1',
    title: 'Software Engineer',
    level: 'IC2',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    template: 'Engineering · Software Engineer · v3',
    headcount: 34,
  },
  {
    id: 2,
    code: 'ENG-SR-1',
    title: 'Senior Software Engineer',
    level: 'IC3',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    template: 'Engineering · Senior SWE · v2',
    headcount: 18,
  },
  {
    id: 3,
    code: 'ENG-EM-1',
    title: 'Engineering Manager',
    level: 'M2',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    template: 'Engineering · Eng Manager · v2',
    headcount: 6,
  },
  {
    id: 4,
    code: 'PRD-PM-1',
    title: 'Product Manager',
    level: 'M1',
    divId: 1,
    dept: 'Product',
    deptId: 2,
    template: 'Product · PM · v3',
    headcount: 9,
  },
  {
    id: 5,
    code: 'DES-PD-1',
    title: 'Product Designer',
    level: 'IC2',
    divId: 1,
    dept: 'Design',
    deptId: 3,
    template: 'Design · Product Designer · v2',
    headcount: 11,
  },
  {
    id: 6,
    code: 'FIN-AC-1',
    title: 'Accountant',
    level: 'IC2',
    divId: 4,
    dept: 'Finance',
    deptId: 5,
    template: 'Finance · Accountant · v1',
    headcount: 6,
  },
  {
    id: 7,
    code: 'ENG-JR-1',
    title: 'Junior Software Engineer',
    level: 'IC1',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    template: 'Engineering · Junior SWE · v1',
    headcount: 24,
  },
];

const squadRows = [
  {
    id: 1,
    code: 'CC',
    name: 'Cart & Checkout',
    divId: 1,
    deptId: 1,
    description: '',
  },
  {
    id: 2,
    code: 'PLT',
    name: 'Platform',
    divId: 1,
    deptId: 1,
    description: '',
  },
  { id: 3, code: 'INF', name: 'Infra', divId: 1, deptId: 1, description: '' },
  {
    id: 4,
    code: 'PAY',
    name: 'Payments',
    divId: 1,
    deptId: 1,
    description: '',
  },
  {
    id: 5,
    code: 'GRW',
    name: 'Growth',
    divId: 1,
    deptId: 1,
    description: '',
  },
  {
    id: 6,
    code: 'DTP',
    name: 'Data Platform',
    divId: 1,
    deptId: 1,
    description: '',
  },
];

const jobTitleRows = [
  { id: 1, code: 'JT-HR', name: 'HR', description: 'Human Resources' },
  { id: 2, code: 'JT-HODIV', name: 'HoDiv', description: 'Head of Division' },
  {
    id: 3,
    code: 'JT-HODEPT',
    name: 'HoDept',
    description: 'Head of Department',
  },
  { id: 4, code: 'JT-SL', name: 'SL', description: 'Squad Leader' },
  {
    id: 5,
    code: 'JT-STAFF',
    name: 'Staff',
    description: 'Individual Contributor',
  },
];

const employeeRows = [
  {
    id: 1,
    nip: 'EMP-2021-0341',
    name: 'Andi Pratama',
    initials: 'AP',
    email: 'andi@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 1,
    orgRole: 'staff',
    status: 'active',
    joined: 'Aug 2021',
    reviewerSlId: 2,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 2,
    nip: 'EMP-2020-0218',
    name: 'Budi Santoso',
    initials: 'BS',
    email: 'budi@performa.id',
    posId: 2,
    deptId: 1,
    divId: 1,
    squadId: 1,
    orgRole: 'sl',
    status: 'active',
    joined: 'Jan 2020',
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 3,
    nip: 'EMP-2018-0042',
    name: 'Citra Dewi',
    initials: 'CD',
    email: 'citra@performa.id',
    posId: 3,
    deptId: 1,
    divId: 1,
    squadId: null,
    orgRole: 'hodept',
    status: 'active',
    joined: 'May 2018',
  },
  {
    id: 4,
    nip: 'EMP-2017-0010',
    name: 'Deni Wahyudi',
    initials: 'DW',
    email: 'deni@performa.id',
    posId: null,
    deptId: 1,
    divId: 1,
    squadId: null,
    orgRole: 'hodiv',
    status: 'active',
    joined: 'Mar 2017',
  },
  {
    id: 5,
    nip: 'EMP-2019-0188',
    name: 'Eka Rahayu',
    initials: 'ER',
    email: 'eka@performa.id',
    posId: null,
    deptId: 6,
    divId: 4,
    squadId: null,
    orgRole: 'hr',
    status: 'active',
    joined: 'Jul 2019',
  },
  {
    id: 6,
    nip: 'EMP-2022-0420',
    name: 'Fani Lestari',
    initials: 'FL',
    email: 'fani@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 1,
    orgRole: 'staff',
    status: 'active',
    joined: 'Jun 2022',
    reviewerSlId: 2,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 7,
    nip: 'EMP-2023-0815',
    name: 'Gilang Nugraha',
    initials: 'GN',
    email: 'gilang@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 2,
    orgRole: 'staff',
    status: 'active',
    joined: 'Sep 2023',
    reviewerSlId: 2,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 8,
    nip: 'EMP-2025-1102',
    name: 'Levi Pranata',
    initials: 'LP',
    email: 'levi@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 3,
    orgRole: 'staff',
    status: 'onboarding',
    joined: 'Jan 2026',
    reviewerSlId: 2,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 9,
    nip: 'EMP-2026-0001',
    name: 'Aqmal Pratama',
    initials: 'AQ',
    email: 'aqmal@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 1,
    orgRole: 'staff',
    status: 'active',
    joined: 'Jan 2026',
    reviewerSlId: 2,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 10,
    nip: 'EMP-2026-0002',
    name: 'Aqmal Rizky',
    initials: 'AR',
    email: 'aqmal.rizky@performa.id',
    posId: 2,
    deptId: 1,
    divId: 1,
    squadId: 2,
    orgRole: 'sl',
    status: 'active',
    joined: 'Feb 2026',
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 11,
    nip: 'EMP-2026-0003',
    name: 'Aqmal Hakim',
    initials: 'AH',
    email: 'aqmal.hakim@performa.id',
    posId: 3,
    deptId: 1,
    divId: 1,
    squadId: null,
    orgRole: 'hodept',
    status: 'active',
    joined: 'Mar 2026',
  },
  {
    id: 12,
    nip: 'EMP-2026-0004',
    name: 'Aqmal Firdaus',
    initials: 'AF',
    email: 'aqmal.firdaus@performa.id',
    posId: null,
    deptId: 1,
    divId: 1,
    squadId: null,
    orgRole: 'hodiv',
    status: 'active',
    joined: 'Apr 2026',
  },
  {
    id: 13,
    nip: 'EMP-2026-0005',
    name: 'Aqmal Naufal',
    initials: 'AN',
    email: 'aqmal.naufal@performa.id',
    posId: null,
    deptId: 6,
    divId: 4,
    squadId: null,
    orgRole: 'hr',
    status: 'active',
    joined: 'May 2026',
  },
  {
    id: 14,
    nip: 'EMP-2026-0101',
    name: 'Raka Mahendra',
    initials: 'RM',
    email: 'raka.mahendra@performa.id',
    posId: 2,
    deptId: 1,
    divId: 1,
    squadId: 4,
    orgRole: 'sl',
    status: 'active',
    joined: 'May 2026',
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 15,
    nip: 'EMP-2026-0102',
    name: 'Nabila Putri',
    initials: 'NP',
    email: 'nabila.putri@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 4,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 14,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 16,
    nip: 'EMP-2026-0103',
    name: 'Taufik Ramadhan',
    initials: 'TR',
    email: 'taufik.ramadhan@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 4,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 14,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 17,
    nip: 'EMP-2026-0104',
    name: 'Salsa Anindita',
    initials: 'SA',
    email: 'salsa.anindita@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 4,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 14,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 18,
    nip: 'EMP-2026-0105',
    name: 'Ilham Saputra',
    initials: 'IS',
    email: 'ilham.saputra@performa.id',
    posId: 2,
    deptId: 1,
    divId: 1,
    squadId: 5,
    orgRole: 'sl',
    status: 'active',
    joined: 'May 2026',
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 19,
    nip: 'EMP-2026-0106',
    name: 'Maya Larasati',
    initials: 'ML',
    email: 'maya.larasati@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 5,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 18,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 20,
    nip: 'EMP-2026-0107',
    name: 'Dimas Prakoso',
    initials: 'DP',
    email: 'dimas.prakoso@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 5,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 18,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 21,
    nip: 'EMP-2026-0108',
    name: 'Rina Kurnia',
    initials: 'RK',
    email: 'rina.kurnia@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 5,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 18,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 22,
    nip: 'EMP-2026-0109',
    name: 'Bagas Wicaksono',
    initials: 'BW',
    email: 'bagas.wicaksono@performa.id',
    posId: 2,
    deptId: 1,
    divId: 1,
    squadId: 6,
    orgRole: 'sl',
    status: 'active',
    joined: 'May 2026',
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 23,
    nip: 'EMP-2026-0110',
    name: 'Siti Fauziah',
    initials: 'SF',
    email: 'siti.fauziah@performa.id',
    posId: 1,
    deptId: 1,
    divId: 1,
    squadId: 6,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 22,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 24,
    nip: 'EMP-2026-0111',
    name: 'Yudha Permana',
    initials: 'YP',
    email: 'yudha.permana@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 6,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 22,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
  {
    id: 25,
    nip: 'EMP-2026-0112',
    name: 'Kevin Santika',
    initials: 'KS',
    email: 'kevin.santika@performa.id',
    posId: 7,
    deptId: 1,
    divId: 1,
    squadId: 6,
    orgRole: 'staff',
    status: 'active',
    joined: 'May 2026',
    reviewerSlId: 22,
    reviewerHodId: 3,
    reviewerHodivId: 4,
  },
];

const cycleRows = [
  {
    id: 1,
    name: 'Q1 2026 Appraisal',
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    selfDeadline: '2026-03-24',
    status: 'active',
    description: 'Performance review Q1 2026 · semua divisi',
    distributedAt: '2026-01-08',
    totalAppraisals: 4,
    completed: 0,
    inReview: 1,
    draft: 3,
  },
  {
    id: 2,
    name: 'Q4 2025 Appraisal',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    selfDeadline: '2025-12-22',
    status: 'closed',
    description: 'Year-end review · ditutup 12 Jan 2026',
    distributedAt: '2025-10-06',
    totalAppraisals: 2,
    completed: 2,
    inReview: 0,
    draft: 0,
  },
  {
    id: 3,
    name: 'Mid-Year 2026 (H1)',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    selfDeadline: '2026-06-22',
    status: 'draft',
    description: 'Mid-year check-in · belum didistribusikan',
    distributedAt: null,
    totalAppraisals: 0,
    completed: 0,
    inReview: 0,
    draft: 0,
  },
];

const templateRows = [
  {
    id: 1,
    code: 'ENG-SE-V3',
    name: 'Software Engineer',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    posId: 1,
    level: 'L3',
    version: 'v3',
    status: 'published',
    updated: 'Mar 12, 2026',
    usedBy: 34,
    summary: 'Backend & full-stack engineers · individual contributor track',
  },
  {
    id: 2,
    code: 'ENG-SR-V2',
    name: 'Senior Software Engineer',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    posId: 2,
    level: 'L4',
    version: 'v2',
    status: 'published',
    updated: 'Feb 28, 2026',
    usedBy: 18,
    summary: 'Tech leads · expected to drive design and uplift the squad',
  },
  {
    id: 3,
    code: 'PRD-PM-V3',
    name: 'Product Manager',
    divId: 1,
    dept: 'Product',
    deptId: 2,
    posId: 4,
    level: 'M1',
    version: 'v3',
    status: 'published',
    updated: 'Mar 5, 2026',
    usedBy: 9,
    summary: 'PMs across consumer & growth products',
  },
  {
    id: 4,
    code: 'DES-PD-V2',
    name: 'Product Designer',
    divId: 1,
    dept: 'Design',
    deptId: 3,
    posId: 5,
    level: 'L3',
    version: 'v2',
    status: 'draft',
    updated: 'Mar 21, 2026',
    usedBy: 0,
    summary: 'New version under review · adds research weight',
  },
  {
    id: 5,
    code: 'ENG-JR-V1',
    name: 'Junior Software Engineer',
    divId: 1,
    dept: 'Engineering',
    deptId: 1,
    posId: 7,
    level: 'L2',
    version: 'v1',
    status: 'published',
    updated: 'Apr 16, 2026',
    usedBy: 24,
    summary: 'Entry-level engineers · execution-focused with close mentorship',
  },
];

const templateItems = [
  [
    1,
    'KRA-1',
    'Delivery & velocity',
    25,
    'Story points completed vs committed (90% target)',
  ],
  [1, 'KRA-2', 'Code quality', 20, 'PR review cycle time, defect escape rate'],
  [1, 'KRA-3', 'Reliability & on-call', 15, 'P1 incidents owned, MTTR'],
  [1, 'KRA-4', 'Technical depth', 15, 'Design docs authored, RFC reviews'],
  [
    1,
    'KRA-5',
    'Collaboration & mentorship',
    15,
    'Peer feedback, onboarding contribution',
  ],
  [1, 'KRA-6', 'Continuous learning', 10, 'Certifications, internal talks'],
  [
    2,
    'KRA-1',
    'Project leadership',
    30,
    'Initiatives led to ship, on schedule',
  ],
  [
    2,
    'KRA-2',
    'Architecture & design',
    20,
    'Approved RFCs, system reliability',
  ],
  [2, 'KRA-3', 'Code quality & review', 15, 'Review thoroughness, defect rate'],
  [2, 'KRA-4', 'Mentorship & people growth', 15, 'Mentee growth and feedback'],
  [2, 'KRA-5', 'Cross-team collaboration', 10, 'Dependencies unblocked'],
  [
    2,
    'KRA-6',
    'Operational excellence',
    10,
    'Service health, incident prevention, and postmortem quality',
  ],
  [3, 'KRA-1', 'Outcome delivery', 30, 'OKR attainment for owned product area'],
  [4, 'KRA-1', 'Design quality', 30, 'Design crit ratings, ship quality'],
  [
    5,
    'KRA-1',
    'Feature delivery',
    30,
    'Story completion rate and sprint hygiene',
  ],
  [
    5,
    'KRA-2',
    'Code fundamentals',
    20,
    'Code readability, tests, and lint quality',
  ],
  [5, 'KRA-3', 'Debugging & ownership', 20, 'Issue resolution lead time'],
  [5, 'KRA-4', 'Collaboration', 15, 'PR responsiveness and team feedback'],
  [
    5,
    'KRA-5',
    'Learning progress',
    15,
    'Training roadmap completion and learning demo',
  ],
] as const;

const baseKras = [
  [
    'Reduce checkout P95 latency',
    'Bring P95 of /checkout below 220ms across top 3 markets.',
    'P95 < 220ms',
    25,
    4,
    'Hit 248ms after cart refactor.',
  ],
  [
    'Migrate auth to OIDC provider',
    'Cut over remaining services from legacy session-cookie auth.',
    '100% service rollout',
    20,
    5,
    '10 of 10 services migrated.',
  ],
  [
    'Ship Indonesia payment rails',
    'GA launch of two e-wallet rails.',
    'GA · DANA + GoPay',
    20,
    3,
    'DANA in beta, GoPay UAT pending vendor signoff.',
  ],
  [
    'Reduce on-call alerts by 30%',
    'Tune noisy SLOs and alerting.',
    '>= 30% reduction',
    15,
    4,
    'Reached 28% reduction.',
  ],
  [
    'Mentor 2 junior engineers',
    'Weekly 1:1 cadence.',
    '2 IC2 promotion-ready',
    10,
    4,
    '1 mentee promo-ready.',
  ],
  [
    'Deliver quarterly architecture review',
    'Own the Q1 arch review doc.',
    'Review published + presented',
    10,
    5,
    'Delivered Mar 18.',
  ],
] as const;

const reviewerFields = {
  reviewerSlUserId: 2,
  reviewerSlName: 'Budi Santoso',
  reviewerSlInitials: 'BS',
  reviewerHodUserId: 3,
  reviewerHodName: 'Citra Dewi',
  reviewerHodInitials: 'CD',
  reviewerHodivUserId: 4,
  reviewerHodivName: 'Deni Wahyudi',
  reviewerHodivInitials: 'DW',
};

const defaultJobTitleByRole: Record<string, number> = {
  hr: 1,
  hodiv: 2,
  hodept: 3,
  sl: 4,
  staff: 5,
};

const appraisalRows = [
  {
    id: 1,
    userId: 1,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'draft',
    reflection: 'Good quarter overall. Focused on latency and auth migration.',
    submittedAt: null,
    acknowledgedAt: null,
  },
  {
    id: 2,
    userId: 2,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'draft',
    reflection:
      'Leading Cart & Checkout while keeping platform reliability steady.',
    submittedAt: null,
    acknowledgedAt: null,
  },
  {
    id: 3,
    userId: 6,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'sl_review',
    reflection:
      'Submitted appraisal from a team member awaiting Squad Leader review.',
    submittedAt: '2026-03-24T09:00:00.000Z',
    acknowledgedAt: null,
  },
  {
    id: 4,
    userId: 1,
    cycleName: 'Q4 2025 Appraisal',
    cycleShort: 'Q4 · 2025',
    status: 'completed',
    reflection: 'Closed the year strong on reliability.',
    submittedAt: '2025-12-18T08:00:00.000Z',
    acknowledgedAt: '2026-01-08T03:14:00.000Z',
  },
  {
    id: 5,
    userId: 2,
    cycleName: 'Q4 2025 Appraisal',
    cycleShort: 'Q4 · 2025',
    status: 'completed',
    reflection: 'Strong squad leadership cycle.',
    submittedAt: '2025-12-19T07:30:00.000Z',
    acknowledgedAt: '2026-01-09T02:48:00.000Z',
  },
];

async function setSequence(table: string, value: number) {
  await sql.unsafe(
    `SELECT setval(pg_get_serial_sequence('${table}', 'id'), ${value}, true)`
  );
}

async function main() {
  await sql`TRUNCATE audit_entries, evidence, kras, appraisals, kra_template_items, kra_templates, cycles, employees, squads, job_titles, positions, departments, divisions, users RESTART IDENTITY CASCADE`;
  await db.insert(divisions).values(divisionRows);
  await db.insert(departments).values(departmentRows);
  await db
    .insert(users)
    .values(userRows.map((row) => ({ ...row, passwordHash })));
  await db.insert(positions).values(positionRows);
  await db.insert(squads).values(squadRows);
  await db.insert(jobTitles).values(jobTitleRows);
  await db.insert(employees).values(
    employeeRows.map((row) => ({
      ...row,
      jobTitleId: defaultJobTitleByRole[row.orgRole] ?? null,
    }))
  );
  await sql`
    UPDATE users u
    SET employee_id = e.id
    FROM employees e
    WHERE lower(u.email) = lower(e.email)
  `;
  await db.insert(cycles).values(cycleRows);
  await db.insert(kraTemplates).values(templateRows);
  await db.insert(kraTemplateItems).values(
    templateItems.map(([templateId, code, title, weight, kpi], index) => ({
      templateId,
      code,
      title,
      weight,
      kpi,
      sortOrder: index,
    }))
  );
  await db
    .insert(appraisals)
    .values(appraisalRows.map((row) => ({ ...row, ...reviewerFields })));
  let kraId = 1;
  for (const appraisal of appraisalRows) {
    for (const [
      index,
      [title, description, target, weight, selfScore, selfComment],
    ] of baseKras.entries()) {
      const id = kraId++;
      await db.insert(kras).values({
        id,
        appraisalId: appraisal.id,
        title,
        description,
        target,
        weight,
        selfScore,
        selfComment,
        sortOrder: index,
      });
      if (index < 2) {
        await db.insert(evidence).values({
          kraId: id,
          kind: index === 0 ? 'url' : 'file',
          name:
            index === 0
              ? 'Grafana dashboard · checkout P95'
              : 'rfc-2026-checkout-rewrite.pdf',
          date: 'Mar 10',
          url: index === 0 ? 'https://example.com/grafana' : null,
        });
      }
    }
  }
  await db.insert(auditEntries).values([
    {
      appraisalId: 3,
      timestamp: '2026-03-24T09:00:00.000Z',
      actorUserId: 6,
      actorName: 'Fani Lestari',
      actorRole: 'staff',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'sl_review',
    },
    {
      appraisalId: 4,
      timestamp: '2025-12-18T08:00:00.000Z',
      actorUserId: 1,
      actorName: 'Andi Pratama',
      actorRole: 'staff',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'sl_review',
    },
    {
      appraisalId: 4,
      timestamp: '2025-12-22T04:30:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'sl',
      action: 'approve',
      fromStatus: 'sl_review',
      toStatus: 'hod_review',
    },
    {
      appraisalId: 4,
      timestamp: '2026-01-08T03:14:00.000Z',
      actorUserId: 1,
      actorName: 'Andi Pratama',
      actorRole: 'hodiv',
      action: 'approve',
      fromStatus: 'hodiv_review',
      toStatus: 'completed',
    },
    {
      appraisalId: 5,
      timestamp: '2025-12-19T07:30:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'sl',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'hod_review',
    },
    {
      appraisalId: 5,
      timestamp: '2026-01-09T02:48:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'hodiv',
      action: 'approve',
      fromStatus: 'hodiv_review',
      toStatus: 'completed',
    },
  ]);
  await Promise.all([
    setSequence('users', 25),
    setSequence('divisions', 4),
    setSequence('departments', 6),
    setSequence('job_titles', 5),
    setSequence('positions', 7),
    setSequence('employees', 25),
    setSequence('squads', 6),
    setSequence('cycles', 3),
    setSequence('kra_templates', 5),
    setSequence('appraisals', 5),
    setSequence('kras', kraId - 1),
  ]);
  console.log(
    'Seeded Performa demo data with numeric sequence IDs. Demo password is set via SEED_PASSWORD env (default applies in dev only).'
  );
}

await main();
await sql.end();
