import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { db, sql } from '../db/client.js';
import {
  appraisals,
  auditEntries,
  cycles,
  departments,
  divisions,
  employees,
  evidence,
  kras,
  kraTemplateItems,
  kraTemplates,
  positions,
  users,
} from '../db/schema.js';

const passwordHash = await bcrypt.hash('demo1234', 10);

const userRows = [
  {
    id: 1,
    name: 'Andi Pratama',
    initials: 'AP',
    email: 'andi@performa.id',
    role: 'staff',
    dept: 'Engineering',
    div: 'Technology',
    squad: 'Cart & Checkout',
    position: 'Software Engineer · IC2',
  },
  {
    id: 2,
    name: 'Budi Santoso',
    initials: 'BS',
    email: 'budi@performa.id',
    role: 'sl',
    dept: 'Engineering',
    div: 'Technology',
    squad: 'Cart & Checkout',
    position: 'Squad Leader · IC3',
  },
  {
    id: 3,
    name: 'Citra Dewi',
    initials: 'CD',
    email: 'citra@performa.id',
    role: 'hodept',
    dept: 'Engineering',
    div: 'Technology',
    squad: null,
    position: 'Head of Department',
  },
  {
    id: 4,
    name: 'Deni Wahyudi',
    initials: 'DW',
    email: 'deni@performa.id',
    role: 'hodiv',
    dept: 'Technology',
    div: 'Technology',
    squad: null,
    position: 'Head of Division',
  },
  {
    id: 5,
    name: 'Eka Rahayu',
    initials: 'ER',
    email: 'eka@performa.id',
    role: 'hr',
    dept: 'People (HR)',
    div: 'Corporate',
    squad: null,
    position: 'HR Manager',
  },
  {
    id: 6,
    name: 'Fani Lestari',
    initials: 'FL',
    email: 'fani@performa.id',
    role: 'staff',
    dept: 'Engineering',
    div: 'Technology',
    squad: 'Cart & Checkout',
    position: 'Software Engineer · IC1',
  },
  {
    id: 7,
    name: 'Gilang Nugraha',
    initials: 'GN',
    email: 'gilang@performa.id',
    role: 'staff',
    dept: 'Engineering',
    div: 'Technology',
    squad: 'Platform',
    position: 'Software Engineer · IC2',
  },
  {
    id: 8,
    name: 'Levi Pranata',
    initials: 'LP',
    email: 'levi@performa.id',
    role: 'staff',
    dept: 'Engineering',
    div: 'Technology',
    squad: 'Infra',
    position: 'Software Engineer · IC1',
  },
];

const divisionRows = [
  {
    id: 1,
    name: 'Technology',
    head: 'Deni Wahyudi',
    headId: 4,
    headcount: 134,
    departments: ['Engineering', 'Product', 'Design', 'QA'],
  },
  {
    id: 2,
    name: 'Business',
    head: 'Indah R.',
    headId: 0,
    headcount: 68,
    departments: ['Marketing', 'Sales', 'Customer Care'],
  },
  {
    id: 3,
    name: 'Operations',
    head: 'Yusuf P.',
    headId: 0,
    headcount: 47,
    departments: ['Logistics', 'Procurement'],
  },
  {
    id: 4,
    name: 'Corporate',
    head: 'Eka Rahayu',
    headId: 5,
    headcount: 26,
    departments: ['Finance', 'People (HR)', 'Legal'],
  },
];

const departmentRows = [
  {
    id: 1,
    name: 'Engineering',
    division: 'Technology',
    divId: 1,
    headId: 3,
    hod: 'Citra Dewi',
    positions: 6,
    headcount: 84,
  },
  {
    id: 2,
    name: 'Product',
    division: 'Technology',
    divId: 1,
    headId: 0,
    hod: 'Jasmine Putri',
    positions: 4,
    headcount: 32,
  },
  {
    id: 3,
    name: 'Design',
    division: 'Technology',
    divId: 1,
    headId: 0,
    hod: 'Naomi Salim',
    positions: 3,
    headcount: 18,
  },
  {
    id: 4,
    name: 'Marketing',
    division: 'Business',
    divId: 2,
    headId: 0,
    hod: 'Tania K.',
    positions: 5,
    headcount: 21,
  },
  {
    id: 5,
    name: 'Finance',
    division: 'Corporate',
    divId: 4,
    headId: 0,
    hod: 'Maya S.',
    positions: 4,
    headcount: 14,
  },
  {
    id: 6,
    name: 'People (HR)',
    division: 'Corporate',
    divId: 4,
    headId: 5,
    hod: 'Eka Rahayu',
    positions: 3,
    headcount: 12,
  },
];

const positionRows = [
  {
    id: 1,
    code: 'ENG-SE-1',
    title: 'Software Engineer',
    level: 'IC2',
    dept: 'Engineering',
    template: 'Engineering · Software Engineer · v3',
    headcount: 34,
  },
  {
    id: 2,
    code: 'ENG-SR-1',
    title: 'Senior Software Engineer',
    level: 'IC3',
    dept: 'Engineering',
    template: 'Engineering · Senior SWE · v2',
    headcount: 18,
  },
  {
    id: 3,
    code: 'ENG-EM-1',
    title: 'Engineering Manager',
    level: 'M2',
    dept: 'Engineering',
    template: 'Engineering · Eng Manager · v2',
    headcount: 6,
  },
  {
    id: 4,
    code: 'PRD-PM-1',
    title: 'Product Manager',
    level: 'M1',
    dept: 'Product',
    template: 'Product · PM · v3',
    headcount: 9,
  },
  {
    id: 5,
    code: 'DES-PD-1',
    title: 'Product Designer',
    level: 'IC2',
    dept: 'Design',
    template: 'Design · Product Designer · v2',
    headcount: 11,
  },
  {
    id: 6,
    code: 'FIN-AC-1',
    title: 'Accountant',
    level: 'IC2',
    dept: 'Finance',
    template: 'Finance · Accountant · v1',
    headcount: 6,
  },
];

const employeeRows = [
  {
    id: 1,
    nip: 'EMP-2021-0341',
    name: 'Andi Pratama',
    initials: 'AP',
    email: 'andi@performa.id',
    position: 'Software Engineer',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Budi Santoso',
    squad: 'Cart & Checkout',
    grade: 'IC2',
    status: 'active',
    joined: 'Aug 2021',
  },
  {
    id: 2,
    nip: 'EMP-2020-0218',
    name: 'Budi Santoso',
    initials: 'BS',
    email: 'budi@performa.id',
    position: 'Senior Software Engineer',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Citra Dewi',
    squad: 'Cart & Checkout',
    grade: 'IC3',
    status: 'active',
    joined: 'Jan 2020',
  },
  {
    id: 3,
    nip: 'EMP-2018-0042',
    name: 'Citra Dewi',
    initials: 'CD',
    email: 'citra@performa.id',
    position: 'Engineering Manager',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Deni Wahyudi',
    squad: null,
    grade: 'M2',
    status: 'active',
    joined: 'May 2018',
  },
  {
    id: 4,
    nip: 'EMP-2017-0010',
    name: 'Deni Wahyudi',
    initials: 'DW',
    email: 'deni@performa.id',
    position: 'Head of Division',
    dept: 'Technology',
    div: 'Technology',
    division: 'Technology',
    manager: '',
    squad: null,
    grade: 'M3',
    status: 'active',
    joined: 'Mar 2017',
  },
  {
    id: 5,
    nip: 'EMP-2019-0188',
    name: 'Eka Rahayu',
    initials: 'ER',
    email: 'eka@performa.id',
    position: 'HR Manager',
    dept: 'People (HR)',
    div: 'Corporate',
    division: 'Corporate',
    manager: '',
    squad: null,
    grade: 'M2',
    status: 'active',
    joined: 'Jul 2019',
  },
  {
    id: 6,
    nip: 'EMP-2022-0420',
    name: 'Fani Lestari',
    initials: 'FL',
    email: 'fani@performa.id',
    position: 'Software Engineer',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Budi Santoso',
    squad: 'Cart & Checkout',
    grade: 'IC1',
    status: 'active',
    joined: 'Jun 2022',
  },
  {
    id: 7,
    nip: 'EMP-2023-0815',
    name: 'Gilang Nugraha',
    initials: 'GN',
    email: 'gilang@performa.id',
    position: 'Software Engineer',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Budi Santoso',
    squad: 'Platform',
    grade: 'IC2',
    status: 'active',
    joined: 'Sep 2023',
  },
  {
    id: 8,
    nip: 'EMP-2025-1102',
    name: 'Levi Pranata',
    initials: 'LP',
    email: 'levi@performa.id',
    position: 'Software Engineer',
    dept: 'Engineering',
    div: 'Technology',
    division: 'Technology',
    manager: 'Citra Dewi',
    squad: 'Infra',
    grade: 'IC1',
    status: 'onboarding',
    joined: 'Jan 2026',
  },
];

const cycleRows = [
  {
    id: 1,
    name: 'Q1 2026 Appraisal',
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    selfDeadline: '2026-03-24',
    status: 'active',
    description: 'Performance review Q1 2026 · semua divisi',
    distributedAt: '2026-01-08',
    totalAppraisals: 4,
    completed: 0,
    inReview: 1,
    draft: 3,
  },
  {
    id: 2,
    name: 'Q4 2025 Appraisal',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    selfDeadline: '2025-12-22',
    status: 'closed',
    description: 'Year-end review · ditutup 12 Jan 2026',
    distributedAt: '2025-10-06',
    totalAppraisals: 2,
    completed: 2,
    inReview: 0,
    draft: 0,
  },
  {
    id: 3,
    name: 'Mid-Year 2026 (H1)',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    selfDeadline: '2026-06-22',
    status: 'draft',
    description: 'Mid-year check-in · belum didistribusikan',
    distributedAt: null,
    totalAppraisals: 0,
    completed: 0,
    inReview: 0,
    draft: 0,
  },
];

const templateRows = [
  {
    id: 1,
    code: 'ENG-SE-V3',
    name: 'Software Engineer',
    dept: 'Engineering',
    level: 'L3',
    version: 'v3',
    status: 'published',
    updated: 'Mar 12, 2026',
    usedBy: 34,
    summary: 'Backend & full-stack engineers · individual contributor track',
  },
  {
    id: 2,
    code: 'ENG-SR-V2',
    name: 'Senior Software Engineer',
    dept: 'Engineering',
    level: 'L4',
    version: 'v2',
    status: 'published',
    updated: 'Feb 28, 2026',
    usedBy: 18,
    summary: 'Tech leads · expected to drive design and uplift the squad',
  },
  {
    id: 3,
    code: 'PRD-PM-V3',
    name: 'Product Manager',
    dept: 'Product',
    level: 'M1',
    version: 'v3',
    status: 'published',
    updated: 'Mar 5, 2026',
    usedBy: 9,
    summary: 'PMs across consumer & growth products',
  },
  {
    id: 4,
    code: 'DES-PD-V2',
    name: 'Product Designer',
    dept: 'Design',
    level: 'L3',
    version: 'v2',
    status: 'draft',
    updated: 'Mar 21, 2026',
    usedBy: 0,
    summary: 'New version under review · adds research weight',
  },
];

const templateItems = [
  [
    1,
    'KRA-1',
    'Delivery & velocity',
    25,
    'Story points completed vs committed (90% target)',
  ],
  [1, 'KRA-2', 'Code quality', 20, 'PR review cycle time, defect escape rate'],
  [1, 'KRA-3', 'Reliability & on-call', 15, 'P1 incidents owned, MTTR'],
  [1, 'KRA-4', 'Technical depth', 15, 'Design docs authored, RFC reviews'],
  [
    1,
    'KRA-5',
    'Collaboration & mentorship',
    15,
    'Peer feedback, onboarding contribution',
  ],
  [1, 'KRA-6', 'Continuous learning', 10, 'Certifications, internal talks'],
  [
    2,
    'KRA-1',
    'Project leadership',
    30,
    'Initiatives led to ship, on schedule',
  ],
  [
    2,
    'KRA-2',
    'Architecture & design',
    20,
    'Approved RFCs, system reliability',
  ],
  [2, 'KRA-3', 'Code quality & review', 15, 'Review thoroughness, defect rate'],
  [3, 'KRA-1', 'Outcome delivery', 30, 'OKR attainment for owned product area'],
  [4, 'KRA-1', 'Design quality', 30, 'Design crit ratings, ship quality'],
] as const;

const baseKras = [
  [
    'Reduce checkout P95 latency',
    'Bring P95 of /checkout below 220ms across top 3 markets.',
    'P95 < 220ms',
    25,
    4,
    'Hit 248ms after cart refactor.',
  ],
  [
    'Migrate auth to OIDC provider',
    'Cut over remaining services from legacy session-cookie auth.',
    '100% service rollout',
    20,
    5,
    '10 of 10 services migrated.',
  ],
  [
    'Ship Indonesia payment rails',
    'GA launch of two e-wallet rails.',
    'GA · DANA + GoPay',
    20,
    3,
    'DANA in beta, GoPay UAT pending vendor signoff.',
  ],
  [
    'Reduce on-call alerts by 30%',
    'Tune noisy SLOs and alerting.',
    '>= 30% reduction',
    15,
    4,
    'Reached 28% reduction.',
  ],
  [
    'Mentor 2 junior engineers',
    'Weekly 1:1 cadence.',
    '2 IC2 promotion-ready',
    10,
    4,
    '1 mentee promo-ready.',
  ],
  [
    'Deliver quarterly architecture review',
    'Own the Q1 arch review doc.',
    'Review published + presented',
    10,
    5,
    'Delivered Mar 18.',
  ],
] as const;

const reviewerFields = {
  reviewerSlUserId: 2,
  reviewerSlName: 'Budi Santoso',
  reviewerSlInitials: 'BS',
  reviewerHodUserId: 3,
  reviewerHodName: 'Citra Dewi',
  reviewerHodInitials: 'CD',
  reviewerHodivUserId: 4,
  reviewerHodivName: 'Deni Wahyudi',
  reviewerHodivInitials: 'DW',
};

const appraisalRows = [
  {
    id: 1,
    userId: 1,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'draft',
    reflection: 'Good quarter overall. Focused on latency and auth migration.',
    submittedAt: null,
    acknowledgedAt: null,
  },
  {
    id: 2,
    userId: 2,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'draft',
    reflection:
      'Leading Cart & Checkout while keeping platform reliability steady.',
    submittedAt: null,
    acknowledgedAt: null,
  },
  {
    id: 3,
    userId: 6,
    cycleName: 'Q1 2026 Appraisal',
    cycleShort: 'Q1 · 2026',
    status: 'sl_review',
    reflection:
      'Submitted appraisal from a team member awaiting Squad Leader review.',
    submittedAt: '2026-03-24T09:00:00.000Z',
    acknowledgedAt: null,
  },
  {
    id: 4,
    userId: 1,
    cycleName: 'Q4 2025 Appraisal',
    cycleShort: 'Q4 · 2025',
    status: 'completed',
    reflection: 'Closed the year strong on reliability.',
    submittedAt: '2025-12-18T08:00:00.000Z',
    acknowledgedAt: '2026-01-08T03:14:00.000Z',
  },
  {
    id: 5,
    userId: 2,
    cycleName: 'Q4 2025 Appraisal',
    cycleShort: 'Q4 · 2025',
    status: 'completed',
    reflection: 'Strong squad leadership cycle.',
    submittedAt: '2025-12-19T07:30:00.000Z',
    acknowledgedAt: '2026-01-09T02:48:00.000Z',
  },
];

async function setSequence(table: string, value: number) {
  await sql.unsafe(
    `SELECT setval(pg_get_serial_sequence('${table}', 'id'), ${value}, true)`
  );
}

async function main() {
  await sql`TRUNCATE audit_entries, evidence, kras, appraisals, kra_template_items, kra_templates, cycles, employees, positions, departments, divisions, users RESTART IDENTITY CASCADE`;
  await db
    .insert(users)
    .values(userRows.map((row) => ({ ...row, passwordHash })));
  await db.insert(divisions).values(divisionRows);
  await db.insert(departments).values(departmentRows);
  await db.insert(positions).values(positionRows);
  await db.insert(employees).values(employeeRows);
  await db.insert(cycles).values(cycleRows);
  await db.insert(kraTemplates).values(templateRows);
  await db.insert(kraTemplateItems).values(
    templateItems.map(([templateId, code, title, weight, kpi], index) => ({
      templateId,
      code,
      title,
      weight,
      kpi,
      sortOrder: index,
    }))
  );
  await db
    .insert(appraisals)
    .values(appraisalRows.map((row) => ({ ...row, ...reviewerFields })));
  let kraId = 1;
  for (const appraisal of appraisalRows) {
    for (const [
      index,
      [title, description, target, weight, selfScore, selfComment],
    ] of baseKras.entries()) {
      const id = kraId++;
      await db.insert(kras).values({
        id,
        appraisalId: appraisal.id,
        title,
        description,
        target,
        weight,
        selfScore,
        selfComment,
        sortOrder: index,
      });
      if (index < 2) {
        await db.insert(evidence).values({
          kraId: id,
          kind: index === 0 ? 'url' : 'file',
          name:
            index === 0
              ? 'Grafana dashboard · checkout P95'
              : 'rfc-2026-checkout-rewrite.pdf',
          date: 'Mar 10',
          url: index === 0 ? 'https://example.com/grafana' : null,
        });
      }
    }
  }
  await db.insert(auditEntries).values([
    {
      appraisalId: 3,
      timestamp: '2026-03-24T09:00:00.000Z',
      actorUserId: 6,
      actorName: 'Fani Lestari',
      actorRole: 'staff',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'sl_review',
    },
    {
      appraisalId: 4,
      timestamp: '2025-12-18T08:00:00.000Z',
      actorUserId: 1,
      actorName: 'Andi Pratama',
      actorRole: 'staff',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'sl_review',
    },
    {
      appraisalId: 4,
      timestamp: '2025-12-22T04:30:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'sl',
      action: 'approve',
      fromStatus: 'sl_review',
      toStatus: 'hod_review',
    },
    {
      appraisalId: 4,
      timestamp: '2026-01-08T03:14:00.000Z',
      actorUserId: 1,
      actorName: 'Andi Pratama',
      actorRole: 'staff',
      action: 'acknowledge',
      fromStatus: 'acknowledge',
      toStatus: 'completed',
    },
    {
      appraisalId: 5,
      timestamp: '2025-12-19T07:30:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'sl',
      action: 'submit',
      fromStatus: 'draft',
      toStatus: 'hod_review',
    },
    {
      appraisalId: 5,
      timestamp: '2026-01-09T02:48:00.000Z',
      actorUserId: 2,
      actorName: 'Budi Santoso',
      actorRole: 'sl',
      action: 'acknowledge',
      fromStatus: 'acknowledge',
      toStatus: 'completed',
    },
  ]);
  await Promise.all([
    setSequence('users', 8),
    setSequence('divisions', 4),
    setSequence('departments', 6),
    setSequence('positions', 6),
    setSequence('employees', 8),
    setSequence('cycles', 3),
    setSequence('kra_templates', 4),
    setSequence('appraisals', 5),
    setSequence('kras', kraId - 1),
  ]);
  console.log(
    'Seeded Performa demo data with numeric sequence IDs. Password for all users: demo1234'
  );
}

await main();
await sql.end();
